"""Export the complete edge set of K_G for the manuscript appendix.

Standalone: `python analysis/export_edges.py`

Table III of the paper shows selected edges only; the camera-ready paper
(Section IV-D) points to this repository for the complete set. This writes the
full set in three formats:

    outputs/edges_full.csv    machine readable
    outputs/edges_full.tex    LaTeX longtable, drop into the appendix
    outputs/edges_full.tsv    tab separated, paste into Word and convert to table

The gloss column is a one-line paraphrase written by the authors. ADA guideline
text is never reproduced: the Standards of Care may not be redistributed.
"""
from __future__ import annotations

import csv
import sys
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT / "src"))

from depgraph.edges import EDGES  # noqa: E402
from depgraph.runlog import RunLog  # noqa: E402
from depgraph.nodes import TIER  # noqa: E402

GRADE_LABEL = {"A": "A", "B": "B", "C": "C", "E": "E", "-": "narrative"}


def rows():
    for i, e in enumerate(sorted(EDGES, key=lambda x: ("ABCE-".index(x.grade), x.src, x.dst)), 1):
        yield {
            "n": i,
            "source": e.src,
            "source_tier": TIER.get(e.src, "?"),
            "target": e.dst,
            "target_tier": TIER.get(e.dst, "?"),
            "grade": GRADE_LABEL[e.grade],
            "ada_source": e.source,
            "gloss": " ".join(e.gloss.split()),
        }


def main(out_dir: Path) -> None:
    log = RunLog("export_edges")
    out_dir.mkdir(parents=True, exist_ok=True)
    data = list(rows())

    with open(out_dir / "edges_full.csv", "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(data[0]))
        w.writeheader()
        w.writerows(data)

    with open(out_dir / "edges_full.tsv", "w") as fh:
        fh.write("\t".join(["#", "Source", "Target", "Grade", "ADA source", "Gloss"]) + "\n")
        for r in data:
            fh.write("\t".join([str(r["n"]), r["source"], r["target"], r["grade"],
                                r["ada_source"], r["gloss"]]) + "\n")

    esc = lambda s: s.replace("&", r"\&").replace("%", r"\%").replace("_", r"\_")
    with open(out_dir / "edges_full.tex", "w") as fh:
        fh.write("% Auto-generated by analysis/export_edges.py. Do not edit by hand.\n")
        fh.write("\\begin{table*}[t]\n\\caption{The complete edge set of $K_G$. "
                 "Every edge asserts that acting on the source is a guideline-recognised "
                 "route to changing the target. Grade is the value the ADA Professional "
                 "Practice Committee assigned to the cited recommendation; \\emph{narrative} "
                 "marks an edge supported by section text rather than a numbered "
                 "recommendation, and is not graded.}\n")
        fh.write("\\label{tab:edges-full}\n\\centering\\scriptsize\n")
        fh.write("\\begin{tabular}{@{}lllp{9.2cm}@{}}\n\\toprule\n")
        fh.write("\\textbf{Edge} & \\textbf{Grade} & \\textbf{ADA source} & "
                 "\\textbf{What the recommendation licenses} \\\\\n\\midrule\n")
        for r in data:
            # Same abbreviations as the manuscript appendix, so regenerating the
            # table reproduces what the paper prints.
            src = r["ada_source"].replace("SoC 2026, ", "").replace(" narrative", " narr.")
            gloss = " ".join(r["gloss"].split())
            if len(gloss) > 96:
                gloss = gloss[:93].rstrip(" ,.;") + "..."
            fh.write(f"\\texttt{{{esc(r['source'])}}} $\\rightarrow$ "
                     f"\\texttt{{{esc(r['target'])}}} & {esc(r['grade'])} & "
                     f"{esc(src)} & {esc(gloss)} \\\\\n")
        fh.write("\\bottomrule\n\\end{tabular}\n\\end{table*}\n")

    c = Counter(r["grade"] for r in data)
    pairs = {(r["source"], r["target"]) for r in data}
    dup = len(data) - len(pairs)
    print(f"{len(data)} edges over {len(pairs)} distinct source-target pairs "
          f"({dup} pairs asserted twice)")
    print("  by grade: " + ", ".join(f"{k}={v}" for k, v in sorted(c.items())))
    into_indicator = sum(1 for r in data if r["target_tier"] == "indicator")
    narr_into_ind = sum(1 for r in data if r["grade"] == "narrative"
                        and r["target_tier"] == "indicator")
    print(f"  edges ending in the indicator tier: {into_indicator}")
    print(f"  narrative edges ending in the indicator tier: {narr_into_ind} "
          f"of {c['narrative']}")
    print(f"  edges ORIGINATING in the indicator tier: "
          f"{sum(1 for r in data if r['source_tier'] == 'indicator')}")
    for f in ("edges_full.csv", "edges_full.tex", "edges_full.tsv"):
        print(f"-> {out_dir / f}")
    log.finish()


if __name__ == "__main__":
    main(Path(sys.argv[1]) if len(sys.argv) > 1 else ROOT / "outputs")
