"""Emit Appendix A: the full edge set of K_G, as a LaTeX longtable.

Standalone: `python analysis/export_edges_tex.py`
Writes analysis/tables/appendix_edges.tex, to be \\input into the manuscript.

WHY A SEPARATE SCRIPT
---------------------
export_edges.py truncates the gloss at 96 characters, which is fine for a
console listing and wrong for print: the longest gloss here is 142 characters
and the point of the appendix is that every edge can be checked against its
source. This script reads depgraph.edges directly and truncates nothing.

The table is generated rather than typed so that it cannot drift from the graph
the experiments use. If the edge set changes, rerun and the appendix follows.
"""
from __future__ import annotations
import sys
import re
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from depgraph.edges import EDGES
from depgraph.nodes import TIER

OUT = Path(__file__).parent / "tables"
OUT.mkdir(exist_ok=True)

TIER_SHORT = {"lever": "L", "treatable": "T", "indicator": "I", "immutable": "M"}
GRADE_LABEL = {"-": "narr."}


def brk(s: str) -> str:
    r"""Insert discretionary hyphens at camelCase boundaries.

    Feature names such as HvyAlcoholConsump are single unhyphenatable tokens.
    In a narrow p{} column TeX cannot break them, so they run past the column
    edge and print on top of the next cell. \- gives TeX legal break points
    without changing what the reader sees when the name does fit on one line.
    """
    return re.sub(r"(?<=[a-z])(?=[A-Z])", r"\\-", s)


def esc(s: str) -> str:
    for a, b in (("&", r"\&"), ("%", r"\%"), ("_", r"\_"), ("#", r"\#"),
                 ("$", r"\$"), ("{", r"\{"), ("}", r"\}")):
        s = s.replace(a, b)
    return s.replace("5-7", "5--7").replace("--", "--")


rows = []
for i, e in enumerate(sorted(EDGES, key=lambda x: (x.source, x.src, x.dst)), 1):
    rows.append(
        "%d & %s\\,(%s) & %s\\,(%s) & %s & %s & %s \\\\" % (
            i,
            brk(esc(e.src)), TIER_SHORT.get(TIER.get(e.src), "?"),
            brk(esc(e.dst)), TIER_SHORT.get(TIER.get(e.dst), "?"),
            GRADE_LABEL.get(e.grade, e.grade),
            esc(e.source),
            esc(e.gloss),
        )
    )

n_graded = sum(1 for e in EDGES if e.grade in ("A", "B", "C"))
pairs = len({(e.src, e.dst) for e in EDGES})

tex = r"""%% Generated by analysis/export_edges_tex.py. Do not edit by hand.
%% Column widths: the provenance strings ("SoC 2026, S5, physical activity
%% narrative") are long, so provenance and both node columns must be p{} rather
%% than l or the natural table width overflows \textwidth by about 270pt and
%% longtable shifts the whole block, caption included, off the right margin.
%% \LTleft/\LTright pin the block to the left margin instead of centring it.
\begingroup
\footnotesize
\setlength{\tabcolsep}{4pt}
\setlength{\LTleft}{0pt}
\setlength{\LTright}{\fill}
\setlength{\LTcapwidth}{\textwidth}
%% Ragged right, not justified: these columns are too narrow for justification
%% and \raggedright needs the array package, loaded by the host document.
\begin{longtable}{@{}r >{\raggedright\arraybackslash}p{0.19\textwidth} >{\raggedright\arraybackslash}p{0.15\textwidth} c >{\raggedright\arraybackslash}p{0.17\textwidth} >{\raggedright\arraybackslash}p{0.28\textwidth}@{}}
\caption{The complete edge set of $K_G$. Tier codes: L lever, T treatable,
I indicator, M immutable. Grade is the evidence grade of the recommendation the
edge was extracted from; \emph{narr.} marks an edge drawn from section narrative
rather than from a numbered recommendation. """ + (
    "%d of the %d edges carry a grade, over %d distinct source--target pairs; "
    "the remaining %d do not, and every edge entering the indicator tier is of "
    "that kind." % (n_graded, len(EDGES), pairs, len(EDGES) - n_graded)
) + r"""}
\label{tab:edges}\\
\toprule
& source & target & grade & provenance & basis \\
\midrule
\endfirsthead
\multicolumn{6}{@{}l}{\footnotesize\itshape Table~\ref{tab:edges}, continued}\\
\toprule
& source & target & grade & provenance & basis \\
\midrule
\endhead
\midrule
\multicolumn{6}{r@{}}{\footnotesize\itshape continued on the next page}\\
\endfoot
\bottomrule
\endlastfoot
""" + "\n".join(rows) + "\n\\end{longtable}\n\\endgroup\n"

(OUT / "appendix_edges.tex").write_text(tex, encoding="utf8")
print(f"wrote {OUT / 'appendix_edges.tex'}: {len(EDGES)} edges, "
      f"{n_graded} graded, {pairs} distinct pairs")
